server:
  port: 8080

spring:
  application:
    name: gateway

  mvc:
    problemdetails:
      enabled: true

  cloud:
    gateway:
      server:
        webflux:
          routes:

            - id: exchange
              uri: http://exchange:8080
              predicates:
                - Path=/exchange/**
              filters:
                - StripPrefix=1

            - id: account
              uri: http://account:8080
              predicates:
                - Path=/account/**

            - id: auth
              uri: http://auth:8080
              predicates:
                - Path=/auth/**

            - id: product
              uri: http://product:8080
              predicates:
                - Path=/product/**

            - id: order
              uri: http://order:8080
              predicates:
                - Path=/order/**

          globalcors:
            corsConfigurations:
              '[/**]':
                allowedOrigins: "*"
                allowedHeaders: "*"
                allowedMethods: "*"

logging:
  level:
    root: info
    store: debug
